name: motivation_couch
description: A Flutter app that uses ChatGPT as a motivation coach.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0 # BLoC pattern library
  http: ^0.13.3 # For making HTTP requests
  equatable: ^2.0.3 # For comparing objects
  bubble: ^1.1.9+1
  # Add any other dependencies you might be using

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.2.0 # For testing BLoC
  mockito: ^5.0.16 # For mocking in tests
  build_runner: ^2.1.4 # For code generation with mockito
  flutter_lints: ^2.0.0
  test:

flutter:
  uses-material-design: true
  # Add other Flutter-specific configurations if needed